version: '3.8'

services:
  # Frontend (client)
  client:
    build:
      context: ./client 
      dockerfile: Dockerfile  
    ports:
      - "3000:80"  # http://localhost:3000
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://server:8081

  # Backend (server)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile 
    ports:
      - "8081:8081"  # Express
      - "8082:8082"  # WebSocket 
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD} 
      - DB_NAME=${DB_NAME}

  # Database (MySQL)
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE=${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
